In [12]:
import numpy as np

np_array = np.array([1,2,4,6])
print(type(np_array))
print('Array size',np_array.size)
print('Array dtype',np_array.dtype)
print('Array shape',np_array.shape)
print('Array n dimension',np_array.ndim)

<class 'numpy.ndarray'>
Array size 4
Array dtype int32
Array shape (4,)
Array n dimension 1


In [22]:
arr_array = np.arange(2,20,2)
#print(arr_array)

arr_array_reshaped = arr_array.reshape(3,3)
print(arr_array)
print(arr_array.shape)
print(arr_array.size)
print('Array n dimension',np_array.ndim)

print('----After rechaping----')

print(arr_array_reshaped)
print(arr_array_reshaped.shape)
print(arr_array_reshaped.size)
print('Array n dimension',arr_array_reshaped.ndim)

[ 2  4  6  8 10 12 14 16 18]
(9,)
9
Array n dimension 1
----After rechaping----
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
(3, 3)
9
Array n dimension 2


In [36]:
arr_array = np.arange(2,37,2)
#print(arr_array)

arr_array_reshaped = arr_array.reshape(3,3,2)
print(arr_array)
print(arr_array.shape)
print(arr_array.size)
print('Array n dimension',np_array.ndim)

print('----After rechaping----')

arr_array_reshaped = arr_array.reshape(3,3,2)
print(arr_array_reshaped)
print('Array shape',arr_array_reshaped.shape)
print('Array size',arr_array_reshaped.size)
print('Array n dimension',arr_array_reshaped.ndim)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36]
(18,)
18
Array n dimension 1
----After rechaping----
[[[ 2  4]
  [ 6  8]
  [10 12]]

 [[14 16]
  [18 20]
  [22 24]]

 [[26 28]
  [30 32]
  [34 36]]]
Array shape (3, 3, 2)
Array size 18
Array n dimension 3


In [23]:
array = np.arange(1,13)
print(array.size)
reshaped = array.reshape(4,3)
print(reshaped)

12
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [41]:
#class work

array = np.arange(1,49,2)
print('Array size',array.size)
reshaped = array.reshape(4,2,3)
print(reshaped)
print('Array n dimension',reshaped.ndim)

Array size 24
[[[ 1  3  5]
  [ 7  9 11]]

 [[13 15 17]
  [19 21 23]]

 [[25 27 29]
  [31 33 35]]

 [[37 39 41]
  [43 45 47]]]
Array n dimension 3


In [44]:
#numpy linspace
arr = np.linspace(2,5,5)
print(arr)
print(arr.size)

[2.   2.75 3.5  4.25 5.  ]
5


In [49]:
ones_array = np.ones(6)
print(ones_array.reshape(2,3))

zeros_array = np.zeros(10)
print(zeros_array)

[[1. 1. 1.]
 [1. 1. 1.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [56]:
array = np.arange(2,20)
print(array)

array = np.append(array, 40) #to add
print(array)

array = np.delete(array, -2) #to remove (index -2 or 17 do delete 19)
print(array)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 40]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 40]


In [75]:
array_random = np.random.rand(10)
print(array_random)
sorted_array = np.sort(array_random)
print(sorted_array)

random_item = np.random.random()
print("random number", round(random_item * 100,2))

[0.58249793 0.96496363 0.12692714 0.70050297 0.45766942 0.07220481
 0.41170116 0.54033642 0.83844599 0.56817172]
[0.07220481 0.12692714 0.41170116 0.45766942 0.54033642 0.56817172
 0.58249793 0.70050297 0.83844599 0.96496363]
random number 61.33


In [78]:
array_random = np.random.rand(3,4)
print(array_random)
array_random = array_random * 10
print(array_random)


[[0.95326065 0.16821319 0.33745799 0.34042666]
 [0.83712948 0.67862433 0.56707288 0.91316907]
 [0.46864541 0.90393526 0.12722963 0.7639445 ]]
[[9.53260651 1.68213191 3.3745799  3.40426664]
 [8.37129477 6.78624328 5.67072878 9.13169069]
 [4.68645411 9.03935261 1.27229626 7.63944496]]


In [87]:
array_a = np.arange(1,10)
array_b = np.arange(11,20)

print('array_a: ',array_a)
print('array_b: ',array_b)

array_c = array_b - array_a
print('array_c: ',array_c)

array_a:  [1 2 3 4 5 6 7 8 9]
array_b:  [11 12 13 14 15 16 17 18 19]
array_c:  [10 10 10 10 10 10 10 10 10]


In [86]:
array_a = np.arange(1,10)
array_b = np.arange(11,20)

array_a = array_a.reshape(3,3)
array_b = array_b.reshape(3,3)


print('array_a: ',array_a)
print('array_b: ',array_b)
array_c = array_b - array_a
print('array_c: ',array_c)

array_a:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
array_b:  [[11 12 13]
 [14 15 16]
 [17 18 19]]
array_c:  [[10 10 10]
 [10 10 10]
 [10 10 10]]
